### ISSUE TITLE
Questions and feedback ?

### ISSUE THREAD

**Issue by timtensor** [lxy5513/cvToolBox#1] opened 2019-07-11 08:38 UTC
Hi @lxy5513 , i really appreciate the effort you put in to make `cvToolBox` I was interested to compile `Hrnet` but i get always get some error . I had tried to use your standalone `Hrnet` implementation  but failed to run it. Instead i had to try other implementation [smpleHrNEt](https://github.com/stefanopini/simple-HRNet).  And i guess i have to compile `Hrnet` to run the the pose track ?  For me , i dont know what is the issue and why i cant compile it straight forward. So i was wondering if there is something i am missing totally ? 

Error shown now 
```
cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup_linux.py", line 12, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils

```

It would be great otherwise to use the work you have done . I hope you understand . 

Make version 
```
make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```
 And my installed packages 

```
.      Successfully uninstalled tqdm-4.32.2
Successfully installed Cython-0.29.11 Markdown-2.6.11 Pillow-5.1.0 PyYAML-5.1.1 Werkzeug-0.14.1 absl-py-0.2.2 astor-0.6.2 backcall-0.1.0 bleach-1.5.0 certifi-2018.4.16 easydict-1.9 gast-0.2.0 grpcio-1.12.0 html5lib-0.9999999 imageio-2.3.0 ipdb-0.12 ipython-7.6.1 jedi-0.14.0 kiwisolver-1.0.1 matplotlib-3.1.1 numpy-1.14.3 opencv-python-4.1.0.25 parso-0.5.0 pexpect-4.7.0 prompt-toolkit-2.0.9 protobuf-3.5.2 python-dateutil-2.7.3 pytz-2018.4 setproctitle-1.1.10 tensorboard-1.8.0 tornado-5.0.2 tqdm-4.32.1
```
In Ubuntu 18.04

**Comment by lxy5513** [comment] 2019-07-11 08:52
Hi, I will see the problem later, .  
Actually, the complie nms environment is similar to lighttrack environment, you can use it's.  After this, only need add several python package.

**Comment by timtensor** [comment] 2019-07-11 09:17
@lxy5513 , thank you . I was thinking it was more like out of box .

**Comment by lxy5513** [comment] 2019-07-12 02:32
Yes, I am not good at English and English naming   😢

**Comment by timtensor** [comment] 2019-07-12 09:54
@lxy5513 , we are all learning and you have given a good starting point . It is now just to figure out how to run the module ?

**Comment by lxy5513** [comment] 2019-07-12 11:43
@timtensor  do you mean ` compile problem`?, I have already fixed in newest commit

**Comment by timtensor** [comment] 2019-07-15 07:34
Ok i guess you are talking about your implementation of `hrnet` right ?? I still am unable to run the `CVToolBox` , yet

**Comment by lxy5513** [comment] 2019-07-15 07:35
what's the detail problem?

**Comment by timtensor** [comment] 2019-07-15 07:39
Following your instructions i tried , the following . My OS is ubuntu 18.04   I checked , i have `Cython` installed 

```
`/mvp/cvToolBox/kps2d_detection/hr_net/lib$ make
cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup_linux.py", line 12, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
`
```

**Comment by lxy5513** [comment] 2019-07-15 07:47
sorry, my OS is Debian 4.9, cannot reproduce you error. maybe you can try `pip uninstall cython && pip install cython ` or  refer this https://stackoverflow.com/questions/11108461/importerror-no-module-named-cython-distutils

**Comment by timtensor** [comment] 2019-07-15 07:58
Thank you ! I will do a more detailed digging . Could you explain me the path on adding enviroment variable ?? 

```
`export PATH=/path/to/cvToolBox:$PATH

export PYTHONPATH=/path/to/cvToolBox:$PYTHONPATH

`
```
My CVtoolBox is located in the fhe following folder structure 

`/home/test/mvp/cvToolBox`

Should i replace `/path/to/cvToolBox` with `/home/test/mvp/cvToolBox` ?

**Comment by lxy5513** [comment] 2019-07-15 08:02
yes, after add environment, you can call pose estimator module , yolov3 module, test image and video in anywhere, It's convenient to the project.

**Comment by timtensor** [comment] 2019-07-15 08:08
I realized that , i have different version of python ( `python2.7` and `python3.6`) Do you think i should create ,  a virtual env ? I think , as you dont see an error , the issues i am facing is because of installation packages

**Comment by lxy5513** [comment] 2019-07-15 08:10
yes, you can create a new conda virtual env

**Comment by timtensor** [comment] 2019-07-15 08:30
Thanks I created a `virtualenv ` using `pip3` . I seem to have no error in compiling the `2d keypoint` module - 
But i get the following , error while downloading the weights  . I was wondering what could be the issue 

```
cvToolBox/pose_track/lighttrack$ python demo.py -p 0 
PoseTrack order.
cvToolBox/pose_track/lighttrack/graph/gcn_utils/io.py:43: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
[07.15.19|10:24:43] Load weights from ./weights/GCN/epoch210_model.pt.
[07.15.19|10:24:43] Load weights [A].
[07.15.19|10:24:43] Load weights [data_bn.weight].
[07.15.19|10:24:43] Load weights [data_bn.bias].
[07.15.19|10:24:43] Load weights [data_bn.running_mean].
[07.15.19|10:24:43] Load weights [data_bn.running_var].
[07.15.19|10:24:43] Load weights [data_bn.num_batches_tracked].
[07.15.19|10:24:43] Load weights [st_gcn_networks.0.gcn.conv.weight].
[07.15.19|10:24:43] Load weights [st_gcn_networks.0.gcn.conv.bias].
[07.15.19|10:24:43] Load weights [st_gcn_networks.1.gcn.conv.weight].
[07.15.19|10:24:43] Load weights [st_gcn_networks.1.gcn.conv.bias].
[07.15.19|10:24:43] Load weights [edge_importance.0].
[07.15.19|10:24:43] Load weights [edge_importance.1].
[07.15.19|10:24:43] Load weights [fcn.weight].
[07.15.19|10:24:43] Load weights [fcn.bias].
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    from kps2d_detection.pose_utils import resize_img
ModuleNotFoundError: No module named 'kps2d_detection'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by lxy5513** [comment] 2019-07-15 08:32
you need adding enviroment variable, 
in python script, print('sys.path'), make sure the path `/home/test/mvp/cvToolBox` in there

**Comment by timtensor** [comment] 2019-07-15 13:17
Thank you ! I actuallly appended the system path in the `demo.py` code.
`sys.path.append("/home/cvToolBox")`
 The issue i have is in the video file . I guess the video has to be in the `data` folder since i get the following error on executing the command 

`python demo.py 0 `

```
  File "demo.py", line 387, in <module>
    parser.add_argument('--video', '-v', type=str, dest='video_path', default=os.path.join(os.environ.get("CVTOOLBOX"), 'data/football.mp4'))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by lxy5513** [comment] 2019-07-16 00:39
0 will be regard as str，you need edit script if you want to use local camera

**Comment by timtensor** [comment] 2019-07-16 07:34
ok , If i want to run a video locally , what changes have to be made ? I plan to download a clip from youtube for ex. I ran the `--help` option to list out the following 

```
demo.py [-w WORK_DIR] [-c CONFIG] [--use_gpu USE_GPU]
               [--device DEVICE [DEVICE ...]] [--print_log PRINT_LOG]
               [--save_log SAVE_LOG] [--model MODEL] [--model_args MODEL_ARGS]
               [--weights WEIGHTS]
               [--ignore_weights IGNORE_WEIGHTS [IGNORE_WEIGHTS ...]]
               [--video VIDEO_PATH] [--pose_detector POSE_DETECTOR]
```

**Comment by lxy5513** [comment] 2019-07-16 07:35
python demo.py --video VIDEO_PATH

**Comment by timtensor** [comment] 2019-07-16 07:44
I tired the following , 
`python demo.py --video /home/cvToolBox/test.mp4 `
Test vid located above but I get the error 

```
  File "demo.py", line 162
SyntaxError: Non-ASCII character '\xe6' in file demo.py on line 162, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by lxy5513** [comment] 2019-07-17 09:11
add # -*- coding: UTF-8 -*- in file header, or use python3

**Comment by timtensor** [comment] 2019-07-17 10:01
Hi Actually i had run it with python 3.6. and i still have some issue . Please let me know if the command i am using is correct. I used the command 
` python3.6 demo.py --video '/home/test/cvToolBox/test.mp4'` I also did a print of the variables and dependencies in my virtual enviroment which looks as follows 
```

``['/home//test/cvToolBox/pose_track/lighttrack', '/home/test/cvToolBox', '/home/test/cvToolBox/pose_track/lighttrack', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '', '/home//myvenv/lib/python3.6/site-packages', '/home//myvenv/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg', '/home//myvenv/lib/python3.6/site-packages/IPython/extensions', '/home//.ipython', '/home/test/cvToolBox']
PoseTrack order.
```
It seems all the variables seem to be imported 
 And the error seem to be 

```
    parser.add_argument('--video', '-v', type=str, dest='video_path', default=os.path.join(os.environ.get("CVTOOLBOX"), 'data/football.mp4'))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
Maybe the command i am executing is wrong .

**Comment by lxy5513** [comment] 2019-07-18 01:54
print(os.path.join(os.environ.get("CVTOOLBOX"), 'data/football.mp4')) or edit default="/home/test/cvToolBox/test.mp4"

**Comment by allendoss** [comment] 2019-07-18 02:10
Have you figured the installation of packages yet? I'm having relative import errors. The files inside `lighttrack` can't access files in upper directory like ones in `kps2d_detection`

**Comment by allendoss** [comment] 2019-07-18 02:11
Where does `cvToolBox` exist? Or are you referring to `cvToolkit`?

**Comment by lxy5513** [comment] 2019-07-18 02:14
Yes, I am sorry, I modified project name to cvToolkit   

you need export env variable 
```
export PATH=/path/to/cvToolkit:$PATH
export PYTHONPATH=/path/to/cvToolkit:$PYTHONPATH
```

**Comment by allendoss** [comment] 2019-07-18 02:51
Thanks that works. I get this error after downloading weights files and running python demo.py -p 1
![image](https://user-images.githubusercontent.com/28283132/61425584-62cba080-a8e5-11e9-97a4-a1e25ac38600.png)

**Comment by lxy5513** [comment] 2019-07-18 03:17
emmm, this is a another question, you run script in server by ssh, but image display can't pass to you local machine. you cam refer this https://askubuntu.com/questions/1130281/how-do-i-display-an-image-in-ssh-terminal

**Comment by timtensor** [comment] 2019-07-18 07:51
@allendoss  not yet i seem to run into some issues but i am documenting them . 
@lxy5513  following your instructions . above i changed the default path to the test video , but for the 2D detection i still need to manually download the pre trained weights is it ?? 

Error 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/test/cvToolBox/kps2d_detection/simple_baseline/models/pytorch/pose_resnet_50_384x288.pth.tar'`

**Comment by lxy5513** [comment] 2019-07-18 07:55
see this: https://github.com/lxy5513/cvToolkit/tree/master/doc

**Comment by timtensor** [comment] 2019-07-18 08:19
@lxy5513 thank you ! finally i managed to run  it . Thanks for your tips . I will try to document all the steps perhaps , so that is easier for others ?  And for further queries , I can perhaps open a new ticket.

**Comment by lxy5513** [comment] 2019-07-18 08:21
@timtensor  that's great.

**Closed as completed** 2019-07-18 08:21 UTC

**Comment by timtensor** [comment] 2019-07-18 08:37
Just a related question , Is there a mail ID one can contact you on ??

**Comment by lxy5513** [comment] 2019-07-18 09:01
OK, my mail ID is lxy5513@gmail.com
